# -*- coding: utf-8 -*-
"""Book Recommendation System - Project 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13N1u1O9jzhpK22SOkp-hEPofv0MTBGbV
"""

books = [
    {"title": "Harry Potter", "genres": ["fantasy", "magic", "adventure"]},
    {"title": "The Hobbit", "genres": ["fantasy", "adventure"]},
    {"title": "Dune", "genres": ["sci-fi", "adventure"]},
    {"title": "Pride and Prejudice", "genres": ["romance", "drama"]},
    {"title": "The Alchemist", "genres": ["adventure", "inspirational"]},
    {"title": "Percy Jackson", "genres": ["fantasy", "mythology", "adventure"]},
    {"title": "The Hunger Games", "genres": ["action", "adventure"]},
    {"title": "Ender's Game", "genres": ["sci-fi", "action"]},
    {"title": "The Fault in Our Stars", "genres": ["romance", "drama"]},
    {"title": "To Kill a Mockingbird", "genres": ["drama"]}
]

print("Book database loaded successfully")

user_input = input("Enter your favorite genres separated by commas: ")

user_preferences = user_input.lower().split(",")

for genre in user_preferences:
    print(genre.strip())

recommendations = []

for book in books:
    score = 0

    for preference in user_preferences:
        if preference.strip() in book["genres"]:
            score += 1

    if score > 0:
        recommendations.append((book["title"], score))

recommendations.sort(key=lambda x: x[1], reverse=True)

print("\nTop 3 Recommended Books:")

for title, score in recommendations[:3]:
    print(f"{title} (Match Score: {score})")